FROM node:16

ENV MONGODB_CONNECTION_PROTOCOL mongodb+srv
# ENV MONGODB_DB_NAME gha-demo1
# ENV MONGODB_CLUSTER_ADDRESS cluster0.ntrwp.mongodb.net
# ENV MONGODB_USERNAME maximilian
# ENV MONGODB_PASSWORD eI3R3UfNlJgWJe17
ENV MONGODB_DB_NAME gha-demo1
ENV MONGODB_CLUSTER_ADDRESS testcluster0.u7uv6ug.mongodb.net
ENV MONGODB_USERNAME dirkleitner
ENV MONGODB_PASSWORD CTWMYV6OKFt1hZKM
WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

CMD ["npm", "start"]